name: flutter_navigation_generator
description: Generate your Flutter navigator by annotating your screen widgets
version: 2.2.1
homepage: https://github.com/ikbendewilliam/flutter_navigation_generator
repository: https://github.com/ikbendewilliam/flutter_navigation_generator
issue_tracker: https://github.com/ikbendewilliam/flutter_navigation_generator/issues

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  analyzer: ">=7.7.1 <10.0.0"
  build: ">=4.0.0 <5.0.0"
  code_builder: ">=4.11.0 <5.0.0"
  collection: ">=1.19.1 <2.0.0"
  dart_style: ">=3.0.0 <4.0.0"
  glob: ">=2.1.3 <3.0.0"
  path: ">=1.9.1 <2.0.0"
  source_gen: ">=3.1.0 <5.0.0"
  flutter_navigation_generator_annotations:
    path: ../flutter_navigation_generator_annotations

dev_dependencies:
  coverage: ^1.6.3
  test: ^1.24.4
  flutter_lints: ^2.0.0

# Comment before publishing
dependency_overrides:
  flutter_navigation_generator_annotations: 
    path: ../flutter_navigation_generator_annotations
